CREATE TABLE IF NOT EXISTS `zhihu_keyword` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `keyword` VARCHAR(255) NOT NULL UNIQUE COMMENT '抓取关键词',
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
